# Generated by Django 3.2 on 2022-01-19 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name Of List')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('points', models.IntegerField()),
                ('faction', models.CharField(max_length=50, verbose_name='Faction')),
                ('roster', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
                ('numberOfComments', models.ManyToManyField(related_name='roster_comments', to=settings.AUTH_USER_MODEL)),
                ('numberOfDislikes', models.ManyToManyField(related_name='roster_dislikes', to=settings.AUTH_USER_MODEL)),
                ('numberOfLikes', models.ManyToManyField(related_name='roster_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdOn'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('numberOfDislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL)),
                ('numberOfLikes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='roster.rosterlist')),
            ],
            options={
                'ordering': ['createdOn'],
            },
        ),
    ]
