# Generated by Django 3.2 on 2022-02-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('points', models.IntegerField(choices=[(500, '500'), (1000, '1000'), (1500, '1500'), (2000, '2000')])),
                ('faction', models.IntegerField(choices=[(1, 'Space Marine'), (2, 'Orcs'), (3, 'Nids'), (4, 'Adeptus Mechanicus'), (5, 'Chaos')])),
                ('roster', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
                ('numberOfComments', models.ManyToManyField(blank=True, null=True, related_name='roster_comments', to=settings.AUTH_USER_MODEL)),
                ('numberOfDislikes', models.ManyToManyField(blank=True, null=True, related_name='roster_dislikes', to=settings.AUTH_USER_MODEL)),
                ('numberOfLikes', models.ManyToManyField(blank=True, null=True, related_name='roster_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdOn'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('numberOfDislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL)),
                ('numberOfLikes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='roster.rosterlist')),
            ],
            options={
                'ordering': ['createdOn'],
            },
        ),
    ]
