# Generated by Django 3.2 on 2022-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rosterlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterlist',
            name='faction',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='points',
            field=models.IntegerField(choices=[(500, '500'), (1000, '1000'), (1500, '1500'), (2000, '2000')]),
        ),
    ]
