# Generated by Django 3.2 on 2022-02-04 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0002_alter_rosterlist_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterlist',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='numberOfComments',
            field=models.ManyToManyField(default=0, related_name='roster_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
