# Generated by Django 3.2 on 2022-01-31 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0003_auto_20220125_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterlist',
            name='numberOfComments',
            field=models.ManyToManyField(blank=True, null=True, related_name='roster_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='numberOfDislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='roster_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='numberOfLikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='roster_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
