# Generated by Django 3.2 on 2022-02-04 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0003_auto_20220204_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterlist',
            name='numberOfDislikes',
            field=models.ManyToManyField(default=0, related_name='roster_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='numberOfLikes',
            field=models.ManyToManyField(default=0, related_name='roster_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
