# Generated by Django 3.2 on 2022-02-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20220131_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterlist',
            name='slug',
        ),
    ]
