# Generated by Django 3.2 on 2022-02-08 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0006_auto_20220207_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='numberOfComments',
            field=models.ManyToManyField(blank=True, related_name='howManyComments', to=settings.AUTH_USER_MODEL),
        ),
    ]
