# Generated by Django 3.2 on 2022-02-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_comment_numberofcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='numberOfComments',
        ),
    ]
