# Generated by Django 3.2 on 2022-02-15 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0008_remove_comment_numberofcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterlist',
            name='Comments',
            field=models.ManyToManyField(blank=True, related_name='roster_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='Dislikes',
            field=models.ManyToManyField(blank=True, related_name='roster_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rosterlist',
            name='Likes',
            field=models.ManyToManyField(blank=True, related_name='roster_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
